### ISSUE TITLE
Decouple filtering parameters from the estimators

### ISSUE THREAD

**Issue by makism** [makism/dyconnmap#11]
It came into my attention that it would be a nice idea if the parameters `fs`, `fb` (those related to filtering) were decoupled from the estimators themselves.

This way, one can use the estimators with, i.e. preprocessed fMRI time series.

**Comment by stdimitr** [comment]
Ι think this is a nice idea avoiding filtering many times as much as
the number of the adapted connectivity estimators.

**Comment by makism** [comment]
The progress is tracked in the branch [revamp-api](https://github.com/makism/dyfunconn/tree/revamp_api).
