### ISSUE TITLE
Does the name change imply eventual changes in functionality?

### ISSUE THREAD

**Issue by danielegrattarola** [makism/dyconnmap#16]
Hi, 

I notice that you changed the project name and I was wondering if it means that significant changes are on the horizon...

I have a project that depends on dyconnmap and I just wanted to know if I should keep an eye out.

Thanks

**Comment by makism** [comment]
Hey @danielegrattarola 

TLDR; No, not really :-)

I think there aren't any more major changes coming; only fixes and features.
I like using [ResearchGate](https://www.researchgate.net/project/Python-tools-for-Brain-Network-Analysis/update/5e2971c13843b093839cbd7a) to post updates and news for the project, check it out if you like.

The name changed to expand the scope of the module; the methods can be used individually in any modality and project.

Regards,
Makis
