### ISSUE TITLE
Estimate dFC for fMRI?

### ISSUE THREAD

**Issue by JoffJones** [makism/dyconnmap#42]
Hi there,

Thanks for developing this package! I have already found some useful tools for static FC here, but I have been struggling to work out if it is possible to do any dynamic FC analyses for fMRI data? Following up on previous threads https://github.com/makism/dyconnmap/issues/11

If so, I'd be really grateful for some tips to get started. I'd like to start with generating some FC networks from sliding windows.

Many thanks,
Joff

**Comment by makism** [comment]
Hey @JoffJones 

Sorry for the tardy reply. Unfortunately, for now, there's not a direct way to do that.
You can use the helper method `sliding_window_indx` to generate the indices for a sliding window. It constructs a 3d matrix of size: `[window_idx, roi_x, roi_y]`; you can use it to iterate over it and employ an `Estimator` object (i.e. `Corr`) to estimate the connectivity within each sliding window.

Hopefully, this helps you out.

Regards,
Makis

**Comment by JoffJones** [comment]
Hi @makism 

Thanks for the help! It was quite straightforward to construct my own sliding window correlation matrices in the end. It's a shame that I can't analyse these with your package, I haven't managed to find any other Python packages for this and those in Matlab seem somewhat limited. Regardless, it is still a very useful reference point for me to consider in my own analyses.

Thanks again,
Joff
