### ISSUE TITLE
About the proper setting of tvfcg

### ISSUE THREAD

**Issue by balandongiv** [makism/dyconnmap#57]
A question of usage rather than a bug report.

Assume we have a 10sec EEG 14 channels data sampled at 128Hz. The objective is to evaluate the dynamic FC in a non-overlapping time windows of 2s. Given the sync bandwidth of interest is `[1.0, 4.0]`. 

Since, the lowest freq is 1.0Hz with 128Hz sampling rate, Cycle criterion should be equal to 2 (correct me if I am wrong).

Then, my question, what is the correct number for step value? My basic understanding tell me it should be equal to 5? Since, each of the 2sec window contain 256 sample, and moving the window for 5 times will cover all the 256*5 =1280 data points.

Say if it is correct step equal to 5. According to the line below, the total number of sliding windows as calculated from `(n_samples - window_length) / step` is equal to 205.

https://github.com/makism/dyconnmap/blob/88e8893f2ba63fadf23376e3a69400ac2b27edaf/dyconnmap/tvfcgs.py#L261

But this lead to another question, why the `fcgs = np.zeros((windows, n_channels, n_channels))` having the shape of `205,14,14`. Shouldt it be the size of  `5,14,14`?

**Comment by stdimitr** [comment]
δεν μπορεί να έχεις 5 παράθυρα
1280 δείγματα με non- overlapping window 256
άρα έχεις 4 δειγματοληψίες και
περισσεύουν 56 δείγματα

Στις Δευ, 2 Νοε 2020, 18:53 ο χρήστης balandong <notifications@github.com>
έγραψε:

**Comment by balandongiv** [comment]
Thanks for the insight @stdimitr, but I still having difficulty digesting about your explanation. Appreciate if you can point to a good reading material about this topic.

**Comment by makism** [comment]
Hey @balandongiv, I think the method is described at https://www.sciencedirect.com/science/article/abs/pii/S0165027010004875

**Comment by balandongiv** [comment]
Thanks for the article @makism
