### ISSUE TITLE
the test does not run correctly

### ISSUE THREAD

**Issue by albertleemon** [makism/dyconnmap#62]
Dear Makism, 

Hello. 

First of all, thanks for the great tool. 

After installation, I realized the test does not run correctly on my side. Could you have a look the output?
Is there anything I should modify?

slurm@master:/home2/data/dyconn/dyconnmap-master/tests$ ls
data                         test_fc.py
__init__.py                  test_graphs.py
__pycache__                  test_graphs_threshold.py
test_chronnectomics.py       test_sliding_window.py
test_clustering.py           test_ts.py
test_clustering_validity.py  test_tvfcgs.py

slurm@master:/home2/data/dyconn/dyconnmap-master/tests$ nosetests -svd .

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Yours sincerely
Meng

**Comment by makism** [comment]
Hey @albertleemon,

Can you try to run an individual suite test like:
```
nosetests -svd test_fc.py
```

Regards,
Makis

**Comment by makism** [comment]
closing because of lack of feedback
