### ISSUE TITLE
pyedflib fails to read the sample EEG files

### ISSUE THREAD

**Issue by wmvanvliet** [makism/dyconnmap#78]
In your first EEG tutorial, the eegmmidb EEG data is loaded with `pyedflib`. However, the EDF files in that project are not strictly complient, because they contain prefilter information in both the "standard" fields and EDF+ annotation fields. `pyedflib` chokes on them: 

```
>>> import pyedflib
>>> pyedflib.EdfReader('eegmmidb/S001/S001R01.edf')

Traceback (most recent call last):
  File "pyedflib/_extensions/_pyedflib.pyx", line 146, in pyedflib._extensions._pyedflib.CyEdfReader.__init__
  File "pyedflib/_extensions/_pyedflib.pyx", line 207, in pyedflib._extensions._pyedflib.CyEdfReader.open
  File "pyedflib/_extensions/_pyedflib.pyx", line 179, in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok
OSError: eegmmidb/S001/S001R01.edf: the file is not EDF(+) or BDF(+) compliant (Prefilter)
```

I've send a [pull request](https://github.com/holgern/pyedflib/pull/114) to `pyedflib` to address the issue, but how did you work around it when writing the tutorial?

**Comment by makism** [comment]
Thank's for the report, I'll check it out.
I was thinking that the error could be due to an update in pyedflib; but I see you submitted and successfully merged a solution.
The easiest fix for me would be to add a note to use pyedflib from the source until a bug fix release is made.

**Comment by wmvanvliet** [comment]
Unfortunately, it's not merged yet :)

**Comment by makism** [comment]
I am going through the tutorials and updating them where needed.
For now, I think I will just add a dependency to your fork ;)

**Comment by makism** [comment]
Hm, it's still erroneous.
pyEDFlib==0.1.14 seems to work :/
